version: "3.3"

services:
  passnet-profile:
    image: tony16019/passnet-profile:latest
    container_name: passnet-profile
    environment:
      - NODE_ENV=prod
      - SERVER_PORT_LISTENER=8081
      - DATABASE_MYSQL_HOST=20.97.232.173
      - DATABASE_MYSQL_PORT=3306
      - DATABASE_MYSQL_USERNAME=root
      - DATABASE_MYSQL_PASSWORD=root
      - DATABASE_MYSQL_DBNAME=passnet_profile_db
      - GRPC_OPTION_URL=passnet-profile:7071
      - GRPC_OPTION_PACKAGE=consumeEvents
      - PROTOBUF_CONSUME_EVENTS_PATH=/proto/consume-events.proto
    ports:
      - "8081:8081"
      - "7071:7071"

  passet-profile-saga:
    image: tony16019/passnet-profile-saga:latest
    container_name: passnet-profile-saga
    environment:
      - PROFILE=prod
      - PROFILE_SERVICE_GRPC_HOST=passnet-profile
      - PROFILE_SERVICE_GRPC_PORT=7071
      - PROFILE_SAGA_PORT=6161
    ports:
      - "6161:6161"
