version: "3.7"

services:
  passnet-recruitment:
    image: tony16019/passnet-recruitment:latest
    environment:
      - PROFILE=prod
      - DATABASE_URL=jdbc:postgresql://192.168.99.100:5432/passnet_recruitment_db
      - DATABASE_USERNAME=passnet-recruitment-app
      - DATABASE_PASSWORD=tungduong98
      - GRPC_PORT_LISTENER=9090
      - SAGA_GRPC_HOST=passnet-recruitment-saga
      - SAGA_GRPC_PORT=6565
    ports:
      - 8080:8080
      - 9090:9090

  passnet-recruitment-saga:
    image: tony16019/passnet-recruitment-saga:latest
    environment:
      - PROFILE=prod
      - KAFKA_BOOTSTRAP_SERVERS=http://52.148.184.202:9092
      - TOPIC_POST_NEW_JOB_EVENT=post-new-job-event
      - TOPIC_ACCEPT_STUDENT_APPLICATION_EVENT7=accept-student-application-event
      - TOPIC_REMOVE_STUDENT_APPLICATION_EVENT=remove-student-application-event
      - TOPIC_DELETE_JOB_EVENT=delete-job-event
      - KAFKA_SCHEMA_REGISTRY_URL=http://52.148.184.202:8081
      - GRPC_PORT_LISTENER=6565
      - MAIN_SERVICE_GRPC_HOST=passnet-recruitment
      - MAIN_SERVICE_GRPC_PORT=9090
